In [1]:
import random
from math import sqrt
import numpy as np

In [2]:
def frobeniusNorm(mat,row,col):
    sumSq = 0
    for i in range(row):
        for j in range(col):
            sumSq += pow(mat[i][j], 2)
    res = sqrt(sumSq)
    print("Frobenius Norm : "+str(round(res,5)),end="\n")
    return round(res, 5)

m = random.randint(2,1000)
n = random.randint(1,m-1)
rnd = 4

matrix =  np.around(np.array(np.random.uniform(0,9.9,m*n),dtype=float),decimals = rnd).reshape(m,n)
print(m,n)
print(matrix)
print(frobeniusNorm(matrix,m,n))

448 272
[[3.7804 1.6636 6.0108 ... 7.5953 4.9764 4.6985]
 [7.4126 5.1814 3.2216 ... 4.412  0.0734 2.8478]
 [1.5838 1.7548 7.1103 ... 8.0686 4.9106 4.3293]
 ...
 [6.5516 9.0471 3.5165 ... 4.563  4.635  5.7243]
 [7.1193 2.3601 1.4689 ... 0.91   8.8152 1.0229]
 [2.8532 7.4199 4.5593 ... 9.7104 9.0151 8.7814]]
Frobenius Norm : 1999.24439
1999.24439


In [3]:
#Gram-Schmidt Algorithm
#didnt do using rank, so consider that also later

def orthogonal(matrix):
    size = matrix.shape[1]
    for i in range(0,size-1):
        for j in range(i,size):
            print(i,j,np.sum(np.multiply(matrix[:,i],matrix[:,j])))
            if  i == j : 
                print("Skipped at: ",i,j)
                continue
            if np.sum(np.multiply(matrix[:,i],matrix[:,j])) != 0:
                
                return "Not Orthogonal"
    return "Orthogonal"

#---------------------------------------------------------------------------
#using Rank Method
def rank(matrix):
    return np.linalg.matrix_rank(np.transpose(matrix))
def gram_schidth(matrix):
    if rank(matrix) == matrix.shape[1]:
        return "Gram-Schmidth Algo Applicable"
    else :
        return "Not Applicable"
    

In [4]:
def projection(ai, ui):
    return (np.dot(ai,ui)/np.linalg.norm(ui)**2)* ui

def gram_schmith_Q(X):
    Y = []
    for i in range(len(X)):
        temp_vec = X[i]
        proj_vec = np.zeros(len(temp_vec))
        for inY in Y :
            proj_vec += projection(X[i],inY)
        tmp = X[i] - proj_vec
        normalized_Y =  tmp/np.linalg.norm(tmp)
        Y.append(normalized_Y)
    return Y

def gram_schmith_R(Q,matrix):
    R = np.dot(Q,matrix)
    for i in range(R.shape[0]):
        for j in range(R.shape[1]):
            if i > j:
                R[i,j] = 0
    return R 

In [5]:
#each verter is column wise, 
#matrix = np.array([[10, 20, 30], [20, 40, 50], [10,20,0]])
matrix = np.array([[1,1,1],
                   [0,1,0],
                   [1,-1,0]])
print(gram_schidth(matrix))

Gram-Schmidth Algo Applicable


In [6]:
matrix = np.array([[1, 0, 0], [1, 1, 0], [1, 1, 1],[1,1,1]])
Q = gram_schmith_Q(np.transpose(matrix))
Q = np.array(Q)
R = gram_schmith_R(Q,matrix)
print(Q,R,sep="\n")

[[ 5.00000000e-01  5.00000000e-01  5.00000000e-01  5.00000000e-01]
 [-8.66025404e-01  2.88675135e-01  2.88675135e-01  2.88675135e-01]
 [ 1.35973996e-16 -8.16496581e-01  4.08248290e-01  4.08248290e-01]]
[[2.         1.5        1.        ]
 [0.         0.8660254  0.57735027]
 [0.         0.         0.81649658]]
